package principal;

import com.panamahitek.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import jssc.SerialPortEvent;
import jssc.SerialPortEventListener;
import jssc.SerialPortException;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

import Ventanas.*;

public class Interfaz extends javax.swing.JFrame {
    PanamaHitek_Arduino arduinouno = new PanamaHitek_Arduino();
    final XYSeries Serie=new XYSeries("Temperatura Celsius");
    final XYSeries Serie1=new XYSeries("Temperatura Farenheit");
    final XYSeries Serie2=new XYSeries("Temperatura Kelvin");
    final XYSeriesCollection Coleccion=new XYSeriesCollection();
    final XYSeriesCollection Coleccion1=new XYSeriesCollection();
    final XYSeriesCollection Coleccion2=new XYSeriesCollection();
    JFreeChart Grafica;
    JFreeChart Grafica1;
    JFreeChart Grafica2;
    int i=0; 
    float celsius=0,farenheit=0,kelvin=0;
    SerialPortEventListener listener=new SerialPortEventListener() {
        @Override
        public void serialEvent(SerialPortEvent spe) {
            try {
                if (arduinouno.isMessageAvailable()==true){//Si llega un valor
                    i++;
                    celsius=(500*Float.parseFloat(arduinouno.printMessage())/1023);//transformo un string a float
                    //farenheit=(float)((9/5)*celsius+32);
                    //kelvin=(float) (celsius+273.15);
                    System.out.println(celsius);//variable celsius obtiene los valores del sensor
                    Celsius.setText(String.format("%.2f", celsius)+" C");//Etiqueta imprimo C
                    //Farenheit.setText(String.format("%.2f", farenheit)+" F");
                    //Kelvin.setText(String.format("%.2f", kelvin)+" K");
                    Serie.add(i,celsius);
                    //Serie1.add(i,farenheit);
                    //Serie2.add(i,kelvin);
                }
            } catch (SerialPortException ex) {
                Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ArduinoException ex) {
                Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    };
    public Interfaz() {
        initComponents();
        try {
            arduinouno.arduinoRXTX("COM5", 9600, listener); //conexión con el arduino
        } catch (ArduinoException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
        Serie.add(0,0);
            Coleccion.addSeries(Serie);
            //Coleccion1.addSeries(Serie1);
            //Coleccion2.addSeries(Serie2);
            Grafica=ChartFactory.createXYLineChart("Temperatura Celsius vs. Tiempo","Tiempo","Temperatura Celsius",
                    Coleccion,PlotOrientation.VERTICAL, true, true, false);
            //Grafica1=ChartFactory.createXYLineChart("Temperatura Farenheit vs. Tiempo","Tiempo","Temperatura Farenheit",
                    //Coleccion1,PlotOrientation.VERTICAL, true, true, false);
            //Grafica2=ChartFactory.createXYLineChart("Temperatura Kelvin vs. Tiempo","Tiempo","Temperatura Kelvin",
                    //Coleccion2,PlotOrientation.VERTICAL, true, true, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jButton1 = new javax.swing.JButton();
        Temperatura = new javax.swing.JLabel();
        Celsius = new javax.swing.JLabel();
        Farenheit = new javax.swing.JLabel();
        Kelvin = new javax.swing.JLabel();
        Grafico = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Contenido = new javax.swing.JMenuItem();
        Acercade = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Temperatura.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Temperatura.setText("TEMPERATURA ");

        Celsius.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        Celsius.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        Farenheit.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        Farenheit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        Kelvin.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        Kelvin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        //Grafico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/temperatura.jpg"))); // NOI18N
        Grafico.setMaximumSize(new java.awt.Dimension(626, 626));

        jMenu1.setText("Opciones");

        jMenuItem4.setText("Valor límite");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem3.setText("Cerrar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");

        Contenido.setText("Contenido");
        Contenido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContenidoActionPerformed(evt);
            }
        });
        jMenu2.add(Contenido);

        Acercade.setText("Acerda de ...");
        Acercade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcercadeActionPerformed(evt);
            }
        });
        jMenu2.add(Acercade);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Gráfica");

        jMenuItem2.setText("Farenheit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2);

        jMenuItem1.setText("Kelvin");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Kelvin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Farenheit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Celsius, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Temperatura, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Grafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Temperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Celsius, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Farenheit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Kelvin, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Grafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //ChartPanel panel=new ChartPanel(Grafica);
        //JFrame Ventana=new JFrame("Celsius");
        //Ventana.getContentPane().add(panel);
        //Ventana.pack();
        //Ventana.setVisible(true);
        //Ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);        // Solo se cierra la ventana de la graficaTODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ContenidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContenidoActionPerformed
       Contenido contenido=new Contenido();
        contenido.setVisible(true);
        contenido.setSize(325, 350);
    }//GEN-LAST:event_ContenidoActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void AcercadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcercadeActionPerformed
        Acercade acerca=new Acercade();
        acerca.setVisible(true);
        acerca.setSize(325, 350);
    }//GEN-LAST:event_AcercadeActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        //ChartPanel panel1=new ChartPanel(Grafica1);
        //JFrame Ventana1=new JFrame("Farenheit");
        //Ventana1.getContentPane().add(panel1);
        //Ventana1.pack();
        //Ventana1.setVisible(true);
        //Ventana1.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        //ChartPanel panel2=new ChartPanel(Grafica2);
        //JFrame Ventana2=new JFrame("Kelvin");
        //Ventana2.getContentPane().add(panel2);
        //Ventana2.pack();
        //Ventana2.setVisible(true);
        //Ventana2.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        String valor="100";
        int a=0,b=0;
        while (Integer.parseInt(valor)<10 || Integer.parseInt(valor)>90){
            valor=JOptionPane.showInputDialog("Ingrese el valor límite entre 10 y 90");//Ingreso de 2 digitos
        }
        b=Integer.parseInt(""+valor.charAt(0));//Conversion a entero valor de la posicion 
        a=Integer.parseInt(""+valor.charAt(1));
        try {
           arduinouno.sendByte(b);
           arduinouno.sendByte(a);
        } catch (ArduinoException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SerialPortException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Acercade;
    private javax.swing.JLabel Celsius;
    private javax.swing.JMenuItem Contenido;
    private javax.swing.JLabel Farenheit;
    private javax.swing.JLabel Grafico;
    private javax.swing.JLabel Kelvin;
    private javax.swing.JLabel Temperatura;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    // End of variables declaration//GEN-END:variables
}
